name: kartrider_rns
description: A new Flutter project.
publish_to: 'none' 
version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  flutter_native_splash: ^1.2.0
  flutter_screenutil: ^5.0.0+2 # 해상도 별 이미지 및 위젯 크기 자동화
  cupertino_icons: ^1.0.3
  get: ^4.3.0 # GetX (상태관리-1)
  get_storage: ^2.0.3
  provider: ^5.0.0 # provider (상태관리-2)
  english_words: ^4.0.0  # Ctrl + . 기능 (자동으로 import 처리)

  flutter_svg: ^0.22.0
  cached_network_image: ^3.1.0
  quiver: ^3.0.1

  animated_splash_screen: ^1.1.0 # 애니메이션 Splash
  convex_bottom_bar: ^3.0.0 # 애니메이션 탭 (하단)메뉴
  shared_preferences: ^2.0.6 # 사용자의 메일주소와 비밀번호를 저장하기 위해 사용할 플러그인
  logger: ^1.0.0 # 로그을 출력하기 위한 플러그인
  sizer: ^2.0.13 # 다양한 해상도에 맞게 UI를 자동으로 조정해주는 패키지

  material_design_icons_flutter: ^5.0.5955-rc.1
  flutter_feather_icons: ^2.0.0+1
  google_fonts: ^2.1.0

  xml: ^5.1.2 # String 데이터를 받아 파싱을 도와주는 라이브러리
  dio: ^4.0.0 # API 통신을 도와주는 라이브러리.
  pretty_dio_logger: ^1.1.1 
  http: ^0.13.1
  intl: ^0.17.0 # 숫자 포맷을 위한 라이브러리
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.9.1 # 앱 아이콘 변경


flutter:
  uses-material-design: true

  assets:
    - assets/images/


flutter_icons: # 앱 아이콘 설정 # 터미널에서 flutter pub run flutter_launcher_icons:main 입력
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/rns.png" # 앱 아이콘 변경 경로


flutter_native_splash: # 스플래쉬 화면 설정후 flutter pub run flutter_native_splash:create
  android: true
  ios: true
  web: true
  fullscreen: true
  #color: "#2E3131"
  #image: assets/images/splash.png
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  background_image: assets/images/splash.png